services:
  vpnserver:
    # image: taothong/wgserver-vpn:1.0
    build:
      context: .
      dockerfile: dev-VPNserver/Dockerfile   
    deploy:
      resources:
        limits:
          cpus: '${CPU_limits}'       # กำหนดการใช้ CPU         
          memory: '${RAM_limits}'     # กำหนดการใช้ RAM (เช่น 512 MB)
    cpuset: '${NUM_core}'
    container_name: VPNserver
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
      # - "192.168.1.244:51821:51821/tcp"
      - "51000:51000"      
    volumes:
      - ./wg-easy:/etc/wireguard
      - ./iptables-setup.sh:/etc/iptables-setup.sh  # Mount script เข้าสู่ container  
    environment:
      - WG_HOST=172.21.10.200
      - PASSWORD=admin
      - WG_PORT=51000
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=10.0.0.x
      - WG_DEFAULT_DNS=1.1.1.1, 1.1.0.0
      # - WG_ALLOWED_IPS=0.0.0.0/0, 192.168.110.0/24, 192.168.120.0/24, 192.168.130.0/24
      - WG_ALLOWED_IPS=0.0.0.0/0

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # sysctls:
    #   - net.ipv4.conf.all.src_valid_mark=1
    #   - net.ipv4.ip_forward=1
    network_mode: host      
